### ISSUE TITLE
Not work in _clientApi.AuthService.SendCodeAsync(phone)

### ISSUE THREAD

**Issue by hzexe** [OpenTl/OpenTl.ClientApi#1]
` [return: AllowNull]
        public async Task<TResult> SendRequestAsync<TResult>(IRequest<TResult> request, CancellationToken cancellationToken)
        {
            var resultTask = RequestService.RegisterRequest(request, cancellationToken);

            if (**ClientSettings.ConnectionWasInitialize()**)
            {
                await ContextGetter.Context.WriteAndFlushAsync(request);
            }

            return (TResult)await resultTask;
        }`
The method ClientSettings.ConnectionWasInitialize() aways return false,so await resultTask will block it.
how to initialize connection?

**Comment by vik-borisov** [comment]
@hzexe 
Check your code  with this [guide](https://opentl.github.io/OpenTl.ClientApi/Documentation/QuickStart)

**Comment by hzexe** [comment]
Thanks. It works well.

**Comment by emreordukaya** [comment]
can u share please clean code how do u write?
_clientApi.AuthService.SendCodeAsync(phone)
I get error nullreferance.
