### ISSUE TITLE
IsPhoneRegisteredAsync always return true

### ISSUE THREAD

**Issue by micdenny** [OpenTl/OpenTl.ClientApi#11]
If I call `IsPhoneRegisteredAsync` with a number that is not registered on telegram it always return `true`, even if I call it passing a wrong phone number like `0`:

![image](https://user-images.githubusercontent.com/1633595/40244850-4da9c864-5ac4-11e8-9c1f-4ac091107fc6.png)

Am I doing something wrong?

**Comment by hzexe** [comment]
The same trouble

**Comment by hzexe** [comment]
The true value is return from server.
I have test other program，all return the same value now.

**Comment by vik-borisov** [comment]
@hzexe Is it  not a bug?

**Comment by hzexe** [comment]
@vik-borisov 
May be not a bug ,this is same as https://github.com/LonamiWebs/Telethon/issues/778

**Comment by micdenny** [comment]
It seems not to be a bug, so we can close this.
