### ISSUE TITLE
JsonReaderException while calling BuildClientAsync

### ISSUE THREAD

**Issue by jefferyleo** [OpenTl/OpenTl.ClientApi#12]
![image](https://user-images.githubusercontent.com/6831609/40913798-48720f02-6828-11e8-9fd2-92affa08bed5.png)
I've encountered the error as seen in the picture above, all the information of Telegram like apphash, AppId, and Public Key I was copied from [here](https://my.telegram.org/apps). However, I've no idea what cause the error like `Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while parsing value: �. Path '', line 0, position 0.'`
Which the error is not specific enough, got no idea how to debug on this, I hope someone would help me on this. I'm truly appreciate.

**Comment by vik-borisov** [comment]
@jefferyleo try to remove session.dat file

**Comment by jefferyleo** [comment]
@vik-borisov where will be the session.dat file located at? Or just remove the sessionTag?

**Comment by vik-borisov** [comment]
@jefferyleo in "bin" directory

**Comment by jefferyleo** [comment]
@vik-borisov Thanks for the help, I'm appreciated. It works now
