### ISSUE TITLE
error in sendcode

### ISSUE THREAD

**Issue by a-rahmani1998** [OpenTl/OpenTl.ClientApi#16]
![errtel](https://user-images.githubusercontent.com/31850943/44021559-626c56a2-9efa-11e8-9e35-2e86a287067e.PNG)
error in sendcode 
message: 
An existing connection was forcibly closed by the remote host
please help

**Comment by vik-borisov** [comment]
@a-rahmani1998 hi! 
First, check the public key.
Second, the pinging server of telegrams

**Comment by a-rahmani1998** [comment]
@vik-borisov hi bro,
sever of telegram in my country is blocked but Im use vpn and its worked so my error for public key ;
my publick key:
-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAwVACPi9w23mF3tBkdZz+zwrzKOaaQdr01vAbU4E1pvkfj4sqDsm6
lyDONS789sVoD/xCS9Y0hkkC3gtL1tSfTlgCMOOul9lcixlEKzwKENj1Yz/s7daS
an9tqw3bfUV/nqgbhGX81v/+7RFAEd+RwFnK7a+XYl9sluzHRyVVaTTveB2GazTw
Efzk2DWgkBluml8OREmvfraX3bkHZJTKX4EQSjBbbdJ2ZXIsRrYOXfaA+xayEGB+
8hdlLmAjbCVfaigxX0CDqWeR1yFL9kwd9P0NsZRPsmoqVwMbMu7mStFai6aIhc3n
Slv8kg9qv1m6XHVQY3PnEw+QQtqSIXklHwIDAQAB
-----END RSA PUBLIC KEY-----

use in program:
"-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEAwVACPi9w23mF3tBkdZz + zwrzKOaaQdr01vAbU4E1pvkfj4sqDsm6\nlyDONS789sVoD / xCS9Y0hkkC3gtL1tSfTlgCMOOul9lcixlEKzwKENj1Yz / s7daS\nan9tqw3bfUV / nqgbhGX81v / +7RFAEd + RwFnK7a + XYl9sluzHRyVVaTTveB2GazTw\nEfzk2DWgkBluml8OREmvfraX3bkHZJTKX4EQSjBbbdJ2ZXIsRrYOXfaA + xayEGB +\n8hdlLmAjbCVfaigxX0CDqWeR1yFL9kwd9P0NsZRPsmoqVwMbMu7mStFai6aIhc3n\nSlv8kg9qv1m6XHVQY3PnEw + QQtqSIXklHwIDAQAB\n-----END RSA PUBLIC KEY-----"

**Comment by a-rahmani1998** [comment]
!help 
/:
