### ISSUE TITLE
Always get PHONE_NUMBER_FLOOD during code request

### ISSUE THREAD

**Issue by MohammadMDSA** [OpenTl/OpenTl.ClientApi#17]
![image](https://user-images.githubusercontent.com/24609258/44203586-b62cf000-a164-11e8-8584-2c76499f920c.png)

Hi
Every time I try to request for login code, I get PHONE_NUMBER_FLOOD exception... I tried 5 valid numbers in many different ways(98921239XXXX, +98921239XXXX, 98 921239XXXX and ...) and many invalid ones. Always get PHONE_NUMBER_FLOOD exception although this exception is out of context for some of my errors(Like invalid numbers).
Client object is fine and checked appId and appHash for like 100 times.
I'll be very grateful if you help me.:)

**Comment by vik-borisov** [comment]
@MohammadMDSA Hi
Wait for the timeout and try again.

**Comment by MohammadMDSA** [comment]
Switched to Telegram production configuration and the problem was solved.
