### ISSUE TITLE
FileService.DownloadFileAsync()

### ISSUE THREAD

**Issue by mrUlrik** [OpenTl/OpenTl.ClientApi#2]
For the life of me I cannot manage to get this method to download more than 64 KB of data. I have attempted to provide an offset provided through a loop that increases by the file part size.

I then dug into this framework's DownloadFileAsync and see that it generates it's own file part size dependent upon if it is a document or otherwise which would, from my understanding, make my offset invalid. So, I then attempted to take the TFile.Bytes.Length to increase the offset but alas, I am still stuck at 64 KB.

This is where I am at now:

    using (var fs = new FileStream(filename, FileMode.Create, FileAccess.Write))
            {
                // const int filePart = 512 * 1024;

                var largestPhoto = photo.Sizes.Items.Last().Cast<TPhotoSize>();
                if (!(largestPhoto.Location is TFileLocation)) return;

                var downloadDocumentPartSize = 128 * 1024; // 128kb for document
                var downloadPhotoPartSize = 64 * 1024; // 64kb for photo

                var filePartSize = largestPhoto.Location is TInputDocumentFileLocation
                    ? downloadDocumentPartSize
                    : downloadPhotoPartSize;

                var offset = 0;
                var left = largestPhoto.Size;
                while (offset < largestPhoto.Size)
                {
                    Console.WriteLine("Step");
                    Console.WriteLine("Offset: " + offset);
                    var resFile = await _client.FileService.DownloadFileAsync(new TInputFileLocation()
                    {
                        LocalId = largestPhoto.Location.LocalId,
                        Secret = largestPhoto.Location.Secret,
                        VolumeId = largestPhoto.Location.VolumeId
                    });
                    Console.WriteLine("Bytes: " + resFile.Cast<TFile>().Bytes.Length);
                    fs.Write(resFile.Cast<TFile>().Bytes, 0, resFile.Cast<TFile>().Bytes.Length);
                    offset = offset + filePartSize;
                }
                Console.WriteLine("Complete");
            }

I have also attempted to add the offset to FileStream.Write but that did not affect anything. Which would make sense if I'm only receiving 64 KB to begin with. Is this me performing some terrible, basic math or is DownloadFileAsync still a work in progress?

**Comment by vik-borisov** [comment]
https://opentl.github.io/OpenTl.ClientApi/api/OpenTl.ClientApi.Services.Interfaces/IFileService/F64FF93A.html
