### ISSUE TITLE
Establishing connection after termination by exception

### ISSUE THREAD

**Issue by MohammadMDSA** [OpenTl/OpenTl.ClientApi#22]
Socket(connection) exception in another thread (not catch-able) causes the UpdateReceive event not to work anymore and the event doesn't give me updates anymore...

How can I make it work again? (Beside creating another IClientApi instance)
And how can I check connection health during runtime?

Thanks

**Comment by vik-borisov** [comment]
Hi! @MohammadMDSA
Can you create a sample app or test with a bug?

**Comment by vik-borisov** [comment]
@MohammadMDSA Still relevant?

**Comment by MohammadMDSA** [comment]
I started a task that disposes client object every 30minutes and re-instaciate it. It works but definitely not a clean solution...

**Comment by slasher79** [comment]
I was thinking a similar solution. A timer that start after last update received and if no update for a specific time, restart everything. 

Agree with you that it is not a clean solution, but if it works... I also tried implementing a "keepAlive" with a custom request (as was available in previous release) but nothing changes.

One question, Are you using automatic update or manual?

**Comment by slasher79** [comment]
Hello. 

Update on my side. With the keepalive the applicaiton is running smoothly since yesterday. 

KeepAlive Connection, from my point of view, need to be restored.
