### ISSUE TITLE
Rename 'session.dat' File

### ISSUE THREAD

**Issue by dehqan** [OpenTl/OpenTl.ClientApi#25]
Hi, How to rename 'session.dat' file from library?
Is it possible?

Thanks.

**Comment by KoalaBear84** [comment]
Hmm. SesstionTag already works as expected:
![image](https://user-images.githubusercontent.com/5886900/46903936-07472f00-cedd-11e8-87b2-0a1a637014f1.png)

![image](https://user-images.githubusercontent.com/5886900/46903929-f8f91300-cedc-11e8-9a80-829815dc99e9.png)

**Comment by dehqan** [comment]
Yes it works. my mistake.
Thanks!

**Comment by KoalaBear84** [comment]
OK, good. Closing!
