### ISSUE TITLE
How to attach NLog instead of log4net

### ISSUE THREAD

**Issue by dojo90** [OpenTl/OpenTl.ClientApi#27]
My application throwing exceptions during network loosage.

Here you write how to attach a logger into the library: https://github.com/OpenTl/OpenTl.ClientApi/wiki/How-to-attach-a-logger

But this example is only for `log4net`. Culd you provide a way how to implement NLog as well?

**Comment by vik-borisov** [comment]
@dojo90 library supports only log4net
