### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by komailghasemi** [OpenTl/OpenTl.ClientApi#31]
i copied this code in my C# program
👇👇👇
```
var settings = new FactorySettings
{
                AppHash = "49dcbd65b7929a909e4dc955307be7c8",
                AppId = 193693,
                ServerAddress = "185.213.165.19",
                ServerPublicKey = "b0cbcef5a486d9636472ac27f8e11a9d", 
                ServerPort = 443,
                SessionTag = "session", 
                Properties = new ApplicationProperties() 
            };

            clientApi = await ClientFactory.BuildClientAsync(settings);

            if (!clientApi.AuthService.CurrentUserId.HasValue)
            {

                var phone = txtNumber.Text;
                var sentCode = await clientApi.AuthService.SendCodeAsync(phone);
            }
```

But didnt send telegrams code to me !!!

**Comment by boexler** [comment]
`ServerPublicKey` seems to be in wrong format!
`PhoneNumber` must start with a leading `+`. For example `+49` for germany

**Comment by komailghasemi** [comment]
> `ServerPublicKey` seems to be in wrong format!
> `PhoneNumber` must start with a leading `+`. For example `+49` for germany

i know about number 
but  about **ServerPublicKey** 
**ServerPublicKey**  is not mtproto secret key ????

**Comment by boexler** [comment]
You get the `ServerPublicKey` from https://my.telegram.org/apps

See: https://github.com/OpenTl/OpenTl.ClientApi/wiki/Quick-Start

**Comment by komailghasemi** [comment]
> You get the `ServerPublicKey` from https://my.telegram.org/apps
> 
> See: https://github.com/OpenTl/OpenTl.ClientApi/wiki/Quick-Start

oh oh 
yea ...
thx alot
im going to test it
❤❤❤

**Comment by komailghasemi** [comment]
> You get the `ServerPublicKey` from https://my.telegram.org/apps
> 
> See: https://github.com/OpenTl/OpenTl.ClientApi/wiki/Quick-Start

```
            var settings = new FactorySettings
            {
                AppHash = "731...2411417",
                AppId = 1...2,
                ServerAddress = "167.99.44.8",
                ServerPublicKey = @"MIIBCgKCAQEAwVACPi9w23mF3tBkdZz.......SIXklHwIDAQAB",
                ServerPort = 80,
                SessionTag = "session", 
                Properties = new ApplicationProperties() 
            };
            clientApi = await ClientFactory.BuildClientAsync(settings);
            if (!clientApi.AuthService.CurrentUserId.HasValue)
            {
                var phone = txtNumber.Text; 
                var sentCode = await clientApi.AuthService.SendCodeAsync(phone);
            }
```

not working :((

didnt send me the code

**Comment by komailghasemi** [comment]
i wanna use mtproto proxy in my client 
how can i use it with this library ?????

**Comment by emreordukaya** [comment]
why did ou close. if u can use, can u write clean code here please?
