### ISSUE TITLE
CheckCloudPasswordAsync

### ISSUE THREAD

**Issue by komailghasemi** [OpenTl/OpenTl.ClientApi#32]
where is CheckCloudPasswordAsync ????

**Comment by komailghasemi** [comment]
????

**Comment by vik-borisov** [comment]
@komailghasemi 
Hello! 
The new version changed the password transmission mechanism to the server. It is not implemented in the library.

**Comment by theFra985** [comment]
It will be implemented?

**Comment by dehqan** [comment]
Hi,
Is there any way in library to authenticate with password?
I had older version and it was accessible, but after i updated the library, it is not possible.
How can i do this?

**Comment by ghost** [comment]
> 
> 
> @komailghasemi
> Hello!
> The new version changed the password transmission mechanism to the server. It is not implemented in the library.

What is the reason to close the issue then?

**Comment by dehqan** [comment]
> > @komailghasemi
> > Hello!
> > The new version changed the password transmission mechanism to the server. It is not implemented in the library.
> 
> What is the reason to close the issue then?

It's been a while that @vik-borisov had no commits on this repo. I think it is not supported anymore.
