### ISSUE TITLE
join To a Channel

### ISSUE THREAD

**Issue by tabakhian** [OpenTl/OpenTl.ClientApi#39]
first of all thank you for your great work you done here !
i wanted to join to a channel but didnt find any help or source code، I tried to send Custom Request with TlSharp Style but i faild ! can you provide me a way to do that ? 
![image](https://user-images.githubusercontent.com/13492305/61991812-d77fa700-b06a-11e9-9bbf-8967fce2d659.png)
![image](https://user-images.githubusercontent.com/13492305/61991821-e8c8b380-b06a-11e9-8824-8a6e495c88af.png)

your telegram wiki group link is expired ! can i have the new one ?

**Comment by tabakhian** [comment]
find my way , thanks again

**Comment by tabakhian** [comment]
find my way , thanks again 

var req = new RequestJoinChannel
					{
						Channel = new TInputChannel
						{
							ChannelId = channelsSearch.Id,
							AccessHash = (long)channelsSearch.AccessHash
						}
					}

var resJoinChannel = await Infrastructure.TelegramConnection.TelegramClientGet().CustomRequestsService.SendRequestAsync(req).ConfigureAwait(false)

**Comment by imclint21** [comment]
@tabakhian could you give me how do you initialize `channelsSearch`?
