### ISSUE TITLE
An exception in clientApi is caught by the application, but causes the application to crash

### ISSUE THREAD

**Issue by snailrain** [OpenTl/OpenTl.ClientApi#4]
hi,
sorry to disturb you.
I've used openTL for a few days and it's great. I successfully used openTL in my winform program.
However, I have a problem. It makes me very hard.
An exception occurred in openTL, which may be due to network reasons.
My program caught the exception, but my winform still crashed.

**Comment by snailrain** [comment]
How can I make my winform not crash? Thank you very much.

**Comment by vik-borisov** [comment]
Attach the logger, please!
https://github.com/OpenTl/OpenTl.ClientApi/wiki/How-to-attach-a-logger

**Comment by snailrain** [comment]
For example, I disabled the telegram network.
And try-catch all openTL methods use.
Then I recorded the following logs.
I want to catch these exceptions and let winform run normally. But winform crashed. 

"远程主机强迫关闭了一个现有的连接" : Remote host forcibly closed an existing connection.

记录时间：2018-03-30 11:34:50,343 
线程ID:[10] 
日志级别：ERROR 
错误描述：#411304074: Caught exception
 
System.Net.Sockets.SocketException (0x80004005): 远程主机强迫关闭了一个现有的连接。
   在 DotNetty.Transport.Channels.Sockets.SocketChannelAsyncOperation.Validate()
   在 DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)

**Comment by snailrain** [comment]
I recorded in AppDomain.CurrentDomain.UnhandledException.

记录时间：2018-03-30 14:20:49,014 
线程ID:[6] 
日志级别：ERROR 
错误描述：****************************异常文本****************************
【出现时间】：2018/3/30 14:20:49
【异常类型】：SocketException
【异常信息】：Remote host forcibly closed an existing connection.
【堆栈调用】：   在 DotNetty.Transport.Channels.Sockets.TcpSocketChannel.DoWrite(ChannelOutboundBuffer input)
   在 DotNetty.Transport.Channels.AbstractChannel.AbstractUnsafe.Flush0()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 OpenTl.ClientApi.MtProto.Layers.Handshake.Adapters.HandshakeHandlerAdapter.<ChannelActive>d__19.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   在 System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()
   在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
***************************************************************

**Comment by snailrain** [comment]
Why can't I catch it?

**Comment by snailrain** [comment]
**code demo:**

>button_click(){
> Task.Run(()=>{
>   try{
>       openTL.sendMsgAsync().Wait();
>       }
>       catch(Exception ex)
 >      {}
 >   });

**Comment by snailrain** [comment]
AppDomain.CurrentDomain.UnhandledException:

记录时间：2018-03-30 16:54:18,302 
线程ID:[5] 
日志级别：ERROR 
错误描述：****************************异常文本****************************
【出现时间】：2018/3/30 16:54:18
【异常类型】：InvalidOperationException
【异常信息】：[NullGuard] Return value of property 'OpenTl.ClientApi.MtProto.IClientSession OpenTl.ClientApi.Settings.ClientSettings::ClientSession()' is null.
【堆栈调用】：   在 OpenTl.ClientApi.Settings.ClientSettings.get_ClientSession()
   在 OpenTl.ClientApi.MtProto.Layers.Handshake.Adapters.HandshakeHandlerAdapter.<ChannelActive>d__19.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   在 System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   在 System.Threading.ThreadPoolWorkQueue.Dispatch()
   在 System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
***************************************************************

**Comment by snailrain** [comment]
错误描述：#1074812960: Caught exception
 
BarsGroup.CodeGuard.Exceptions.NotExpectedException`1[System.Int32]: The value '255' of 'data' is not expected. Expected value is '256.'
   在 BarsGroup.CodeGuard.Internals.ThrowMessageHelper.ThrowNotEqual[T](ArgBase`1 arg, T expected)
   在 BarsGroup.CodeGuard.ComparableValidatorExtensions.IsEqual[T](ArgBase`1 arg, T param)
   在 OpenTl.Common.Auth.AuthKey..ctor(Byte[] data)
   在 OpenTl.ClientApi.MtProto.Layers.Handshake.Adapters.HandshakeHandlerAdapter.ChannelRead0(IChannelHandlerContext ctx, IObject msg)
   在 DotNetty.Transport.Channels.SimpleChannelInboundHandler`1.ChannelRead(IChannelHandlerContext ctx, Object msg)
   在 DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeChannelRead(Object msg)

**Comment by vik-borisov** [comment]
> 错误描述：#1074812960: Caught exception
> BarsGroup.CodeGuard.Exceptions.NotExpectedException1[System.Int32]: The value '255' of 'data' is not expected. Expected value is '256.' 在 BarsGroup.CodeGuard.Internals.ThrowMessageHelper.ThrowNotEqual[T](ArgBase1 arg, T expected)
> 在 BarsGroup.CodeGuard.ComparableValidatorExtensions.IsEqual[T](ArgBase1 arg, T param) 在 OpenTl.Common.Auth.AuthKey..ctor(Byte[] data) 在 OpenTl.ClientApi.MtProto.Layers.Handshake.Adapters.HandshakeHandlerAdapter.ChannelRead0(IChannelHandlerContext ctx, IObject msg) 在 DotNetty.Transport.Channels.SimpleChannelInboundHandler1.ChannelRead(IChannelHandlerContext ctx, Object msg)
> 在 DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeChannelRead(Object msg)
> 

is it valid exception. Checksum is invalid.

@snailrain recheck all exception on version 0.4.*
