### ISSUE TITLE
HTTP Proxy

### ISSUE THREAD

**Issue by DrBallMD** [OpenTl/OpenTl.ClientApi#6]
Сделайте, пожалуйста, возможность подключения через http proxy

**Comment by vik-borisov** [comment]
@DrBallMD 
We are support Socks5 proxy. 
Why do we need to support http Proxy?

**Comment by DrBallMD** [comment]
Well unfortunately Telegram is blocked by Russian Goverment so I can create http proxy only.

**Comment by vik-borisov** [comment]
@DrBallMD 
You can use any socks5 proxy server. 
e.g. https://www.socks-proxy.net/

**Comment by uracadim** [comment]
@vik-borisov if you can do Http proxy support, it will be great!!! Because it is easier for me to use the IP of my WPA and not to pay money for a proxy.

**Comment by vik-borisov** [comment]
@uracadim 
Http proxy is a solution for http-traffic. This library uses tcp-traffic.
You can install the socks5 proxy server on your VPS and use it.
e.g. https://github.com/wernight/docker-dante

**Comment by vik-borisov** [comment]
@DrBallMD 
@uracadim 
I helped you?

**Comment by GeniusQ** [comment]
@vik-borisov 
How to config the socks5 proxy in OpenTl.ClientApi?
Thank you.
